//1st error//
i have changed my Query table sleect * from to "blocks" instead of my original "states", and we got an error stating it dose not exist!

//2nd error//
changed my schema name to none existing schema, we always need to make sure we have the correct schema name and make sure out schema has table name "states" in "mydb123"

//3rd error//
we need to make sure our root name and password are set up and with the right credentials , and importantly the port need to match in our MAMP as well to get things up and running with no errors


(py2FlaskEnv) Ilyazs-MacBook-Pro:setUp ilyaz$ python server.py
Traceback (most recent call last):
  File "server.py", line 8, in <module>
    print mysql.query_db("SELECT * FROM blocks")
  File "/Users/ilyaz/codingDojo/Python/flask_mySQL/setUp/mysqlconnection.py", line 22, in query_db
    result = self.db.session.execute(text(query), data)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1107, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
sqlalchemy.exc.ProgrammingError: (_mysql_exceptions.ProgrammingError) (1146, "Table 'mydb123.blocks' doesn't exist") [SQL: u'SELECT * FROM blocks']

Traceback (most recent call last):
  File "server.py", line 8, in <module>
    print mysql.query_db("SELECT * FROM states")
  File "/Users/ilyaz/codingDojo/Python/flask_mySQL/setUp/mysqlconnection.py", line 22, in query_db
    result = self.db.session.execute(text(query), data)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1107, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 971, in _connection_for_bind
    engine, execution_options)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 403, in _connection_for_bind
    conn = bind.contextual_connect()
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2103, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2142, in _wrap_pool_connect
    e, dialect, self)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1456, in _handle_dbapi_exception_noconnection
    exc_info
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2138, in _wrap_pool_connect
    return fn()
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 387, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 516, in checkout
    rec = pool._do_get()
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1138, in _do_get
    self._dec_overflow()
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1135, in _do_get
    return self._create_connection()
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 393, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1049, "Unknown database 'mydb12345'")
(py2FlaskEnv) Ilyazs-MacBook-Pro:setUp ilyaz$ python server.py
Traceback (most recent call last):
  File "server.py", line 8, in <module>
    print mysql.query_db("SELECT * FROM states")
  File "/Users/ilyaz/codingDojo/Python/flask_mySQL/setUp/mysqlconnection.py", line 22, in query_db
    result = self.db.session.execute(text(query), data)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1107, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 971, in _connection_for_bind
    engine, execution_options)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 403, in _connection_for_bind
    conn = bind.contextual_connect()
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2103, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2142, in _wrap_pool_connect
    e, dialect, self)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1456, in _handle_dbapi_exception_noconnection
    exc_info
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2138, in _wrap_pool_connect
    return fn()
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 387, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 516, in checkout
    rec = pool._do_get()
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1138, in _do_get
    self._dec_overflow()
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1135, in _do_get
    return self._create_connection()
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 393, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1049, "Unknown database 'mydb12345'")
File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 766, in _checkout
  fairy = _ConnectionRecord.checkout(pool)
File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 516, in checkout
  rec = pool._do_get()
File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1138, in _do_get
  self._dec_overflow()
File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
  compat.reraise(exc_type, exc_value, exc_tb)
File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1135, in _do_get
  return self._create_connection()
File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 333, in _create_connection
  return _ConnectionRecord(self)
File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 461, in __init__
  self.__connect(first_connect_check=True)
File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 651, in __connect
  connection = pool._invoke_creator(self)
File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 105, in connect
  return dialect.connect(*cargs, **cparams)
File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 393, in connect
  return self.dbapi.connect(*cargs, **cparams)
File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
  return Connection(*args, **kwargs)
File "/Users/ilyaz/codingDojo/Python/myEnvironments/py2FlaskEnv/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
  super(Connection, self).__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' (61)")
